on: push
jobs:
  py-app:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v4
      - name: Nombre
        run: echo "Ximena Isaac Horta"
      - name: Version de node
        run: node --version
      - name: Expediente
        run: echo "Expediente: 739032"