on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: node app.js
    container: python:3.8
    steps:
      - uses: actions/checkout@v4
      - run: pyhton3 --version
      - run: python3 archivo.py

